version: '3'
services:
  springboot-docker-compose-app:
    image: shengnianos/springboot-docker-compose-app
#    see: https://github.com/docker/compose/issues/2841
#    links:
#      - shengnianos-mariadb:shengniano-mariadb
    ports:
      - 9440:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://shengnianos-mariadb:3306/sosdocker
      - SOS_SLEEP=10 # gives time for the database to boot before the application
  shengnianos-mariadb:
      image: mariadb:10.1.23
      # volumes:
      #     - ~/volumes/mysql/:/var/lib/mysql/
      environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=123456
          - MYSQL_DATABASE=sosdocker
      ports:
          - 3307:3306
      command: mysqld --lower_case_table_names=1 --skip-ssl
